### ISSUE TITLE
The parameters "-d -e" after ltl2ldba is invalid

### ISSUE THREAD

**Issue by YuanZhuang18** [alperkamil/csrl#1]
I try to run ['ltl2ldba', '-d', '-e', ltl], there is a bug "Multiple unmatched arguments: [-d, -e, (F G a | F G b) & G !c]. To specify
multiple inputs, use the corresponding flags (see --help)."
I delete -d -e, it works. 
However, I think the reward is wrong. In the example "Motion Planning with Safe Absorbing States". If a trace consists of "(0,0),(1,0),(1,1),(1,2),(1,3)" The reward is 0.0. As the describes in the paper, the reward should be 0.01.
I wonder that if the bug is related to the parameters.

**Comment by alperkamil** [comment]
I am so sorry for the late reply. I believe this is a problem related to the newer versions of ltl2ldba. I moved this repository to https://gitlab.oit.duke.edu/cpsl/csrl a while ago.
