### ISSUE TITLE
FileNotFoundError: [WinError 2] No such file or directory "ltl2ldba"

### ISSUE THREAD

**Issue by Bobyue0118** [alperkamil/csrl#2]
FileNotFoundError: [WinError 2] No such file or directory "ltl2ldba"
I have added to PATH, but ltl2ldba no such file or directory.

**Comment by alperkamil** [comment]
I am so sorry for the late reply. You can try to manually add them to ```PATH``` in ```oa.py``` by replacing the 84th line with the following code:
```
env = os.environ.copy()
env["PATH"] = "C:\\rabinizer4\\bin;" + env["PATH"]
out=check_output(['ltl2ldba', '-d', '-e', ltl] if self.oa_type == 'ldba' else ['ltl2dra', '-c', ltl],env=env)
```
Here, I assume ```ltl2ldba``` is under ```"C:\\rabinizer4\\bin;"```, but you can change it with your directory.
